apiVersion: v1
kind: ReplicationController
metadata:
  name: myapprc
  labels:
    app: myapp

spec:
  template:
    metadata:
      name: myapppod
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 3