apiVersion: apps/v1
kind: Deployment
metadata:
  name: myappreplicaset
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      env: prod
  replicas: 3
  template:
    metadata:
      name: nginx2
      labels:
        env: prod
    spec:
      containers:
        - name: nginx-2
          image: nginx