apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-frontend
  labels:
    app: httpdApp
spec:
  selector:
    matchLabels:
      env: deploy

  replicas: 3
  template:
    metadata:
      name: httpd-front 
      labels:
        env: deploy
    spec:
      containers:
        - name: httpd
          image: httpd:2.4-alpine